name: Deploy Free Tier Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    
    - name: Package Lambda functions
      run: |
        cd lambda
        zip -r processor.zip processor.py
        zip -r report.zip report.py

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform plan
      run: terraform plan
      working-directory: terraform
