name: Deploy Free Tier Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 3. Configure AWS credentials (IMPORTANT)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: AKIAVAQK4HDDTT2UXOXE
        aws-secret-access-key: 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
        aws-region: ap-south-1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
